/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Inmueble.Modelo.ConsultasInmueble;
import Inmueble.Controlador.CrlInmueble;
import Vista.Inmueble.FormInmueble;
import Inmueble.Modelo.Inmueble;
import Propietario.Controlador.CtrPropietario;
import Propietario.Modelo.ConsultasPropietario;
import Propietario.Modelo.Propietario;
import Vista.Propietario.panelPropietarioList;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class fromMenu extends javax.swing.JFrame {

   private Propietario propietario=new Propietario();
    private Inmueble inmueble=new Inmueble();
    private static ConsultasPropietario consultasp= new ConsultasPropietario();
    private static ConsultasInmueble consultasi=new ConsultasInmueble();
    private static ArrayList<Inmueble> inmuebles=new ArrayList<Inmueble>();
    private static DefaultTableModel modeloinmuebles;
    
    public fromMenu() {
        initComponents();
        modeloinmuebles=new DefaultTableModel();
        armarCabeceraInmuebles();
        cargarInmuebles();
        
        
        
    }
    public void armarCabeceraInmuebles(){
        ArrayList<Object> columnasi=new ArrayList<Object>();
        columnasi.add("Características");
        columnasi.add("Propietario");
        columnasi.add("Superficie");
        columnasi.add("Precio mensual");
        for(Object col:columnasi)
            modeloinmuebles.addColumn(col);
        tabInmuebles.setModel(modeloinmuebles);
    }
    public static void cargarInmuebles(){
        inmuebles.clear();
        consultasi.obtenerInmuebles(inmuebles);
        borrarInmuebles();
        for(Inmueble i:inmuebles){
            modeloinmuebles.addRow(new Object[] {i.getTipo_inmueble(),i.getPropietario().getApellido_propietario(),i.getSuperficie(),i.getPrecio_base()});
        }
        
    }
    public static void borrarInmuebles(){
        int c=modeloinmuebles.getRowCount()-1;
        for(int i=c;i>=0;i--)
            modeloinmuebles.removeRow(i);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanelContrato = new javax.swing.JPanel();
        jPanelInmueble = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabInmuebles = new javax.swing.JTable();
        btnNuevoInmueble = new javax.swing.JButton();
        jPanelInquilino = new javax.swing.JPanel();
        jPanelPropietario = new javax.swing.JPanel();
        jButtoNuevo = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneMenu.setName("aasds"); // NOI18N
        jTabbedPaneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContratoLayout = new javax.swing.GroupLayout(jPanelContrato);
        jPanelContrato.setLayout(jPanelContratoLayout);
        jPanelContratoLayout.setHorizontalGroup(
            jPanelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanelContratoLayout.setVerticalGroup(
            jPanelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPaneMenu.addTab("Contrato", jPanelContrato);

        tabInmuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabInmuebles);

        btnNuevoInmueble.setText("Nuevo");
        btnNuevoInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoInmuebleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInmuebleLayout = new javax.swing.GroupLayout(jPanelInmueble);
        jPanelInmueble.setLayout(jPanelInmuebleLayout);
        jPanelInmuebleLayout.setHorizontalGroup(
            jPanelInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInmuebleLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnNuevoInmueble)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanelInmuebleLayout.setVerticalGroup(
            jPanelInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInmuebleLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoInmueble)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Inmueble", jPanelInmueble);

        javax.swing.GroupLayout jPanelInquilinoLayout = new javax.swing.GroupLayout(jPanelInquilino);
        jPanelInquilino.setLayout(jPanelInquilinoLayout);
        jPanelInquilinoLayout.setHorizontalGroup(
            jPanelInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanelInquilinoLayout.setVerticalGroup(
            jPanelInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPaneMenu.addTab("Inquilino", jPanelInquilino);

        jButtoNuevo.setLabel("Nuevo");
        jButtoNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtoNuevoMouseClicked(evt);
            }
        });
        jButtoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoNuevoActionPerformed(evt);
            }
        });
        jPanelPropietario.add(jButtoNuevo);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelPropietario.add(jButtonEliminar);

        jTabbedPaneMenu.addTab("Propietario", jPanelPropietario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenu)
        );

        jTabbedPaneMenu.getAccessibleContext().setAccessibleName("Menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMenuMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTabbedPaneMenuMouseClicked

    private void jButtoNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtoNuevoMouseClicked
        // TODO add your handling code here:
        //---- PROPIETARIO
        Propietario pod = new Propietario();
        ConsultasPropietario podP = new ConsultasPropietario ();
        Vista.Propietario.frmPropietario frmP = new Vista.Propietario.frmPropietario();

        CtrPropietario ctrl = new CtrPropietario(pod,podP,frmP);
        ctrl.iniciar();
        this.setEnabled(false);
        //-----------------

        frmP.setVisible(true);
        
    }//GEN-LAST:event_jButtoNuevoMouseClicked

    private void jButtoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoNuevoActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void btnNuevoInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoInmuebleActionPerformed
  
        Inmueble inmueble= new Inmueble();
        FormInmueble formularioinmueble= new FormInmueble();
        ConsultasInmueble consultasinmueble=new ConsultasInmueble();
        CrlInmueble crlinmueble=new CrlInmueble(inmueble,consultasinmueble,formularioinmueble);
        crlinmueble.iniciar();
        formularioinmueble.setVisible(true);
    }//GEN-LAST:event_btnNuevoInmuebleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromMenu().setVisible(true);
                
            }
        });
        
        
     
    }
    
    public void enabledPanel (boolean flag){
         this.setVisible(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoInmueble;
    public javax.swing.JButton jButtoNuevo;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JPanel jPanelContrato;
    private javax.swing.JPanel jPanelInmueble;
    private javax.swing.JPanel jPanelInquilino;
    private javax.swing.JPanel jPanelPropietario;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPaneMenu;
    public javax.swing.JTable tabInmuebles;
    // End of variables declaration//GEN-END:variables
}
