/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Propietario.Controlador.CtrPropietario;
import Propietario.Modelo.ConsultasPropietario;
import Propietario.Modelo.Propietario;
import Vista.Propietario.panelPropietarioList;

/**
 *
 * @author Usuario
 */
public class fromMenu extends javax.swing.JFrame {

    /**
     * Creates new form fromMenu
     */
    public fromMenu() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanelContrato = new javax.swing.JPanel();
        jPanelInmueble = new javax.swing.JPanel();
        jPanelInquilino = new javax.swing.JPanel();
        jPanelPropietario = new javax.swing.JPanel();
        panelPropietarioList1 = new Vista.Propietario.panelPropietarioList();
        jButtonModificar = new javax.swing.JButton();
        jButtoNuevo = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneMenu.setName("aasds"); // NOI18N
        jTabbedPaneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContratoLayout = new javax.swing.GroupLayout(jPanelContrato);
        jPanelContrato.setLayout(jPanelContratoLayout);
        jPanelContratoLayout.setHorizontalGroup(
            jPanelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanelContratoLayout.setVerticalGroup(
            jPanelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPaneMenu.addTab("Contrato", jPanelContrato);

        javax.swing.GroupLayout jPanelInmuebleLayout = new javax.swing.GroupLayout(jPanelInmueble);
        jPanelInmueble.setLayout(jPanelInmuebleLayout);
        jPanelInmuebleLayout.setHorizontalGroup(
            jPanelInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanelInmuebleLayout.setVerticalGroup(
            jPanelInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPaneMenu.addTab("Inmueble", jPanelInmueble);

        javax.swing.GroupLayout jPanelInquilinoLayout = new javax.swing.GroupLayout(jPanelInquilino);
        jPanelInquilino.setLayout(jPanelInquilinoLayout);
        jPanelInquilinoLayout.setHorizontalGroup(
            jPanelInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanelInquilinoLayout.setVerticalGroup(
            jPanelInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPaneMenu.addTab("Inquilino", jPanelInquilino);

        jButtonModificar.setText("Modificar");

        jButtoNuevo.setLabel("Nuevo");
        jButtoNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtoNuevoMouseClicked(evt);
            }
        });
        jButtoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoNuevoActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanelPropietarioLayout = new javax.swing.GroupLayout(jPanelPropietario);
        jPanelPropietario.setLayout(jPanelPropietarioLayout);
        jPanelPropietarioLayout.setHorizontalGroup(
            jPanelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropietarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtoNuevo)
                .addGap(95, 95, 95)
                .addComponent(jButtonEliminar)
                .addGap(22, 22, 22))
            .addGroup(jPanelPropietarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelPropietarioList1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPropietarioLayout.createSequentialGroup()
                    .addGap(352, 352, 352)
                    .addComponent(jButtonModificar)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );
        jPanelPropietarioLayout.setVerticalGroup(
            jPanelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropietarioLayout.createSequentialGroup()
                .addComponent(panelPropietarioList1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoNuevo)
                    .addComponent(jButtonEliminar))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPropietarioLayout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addComponent(jButtonModificar)
                    .addContainerGap(172, Short.MAX_VALUE)))
        );

        jTabbedPaneMenu.addTab("Propietario", jPanelPropietario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenu)
        );

        jTabbedPaneMenu.getAccessibleContext().setAccessibleName("Menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMenuMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTabbedPaneMenuMouseClicked

    private void jButtoNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtoNuevoMouseClicked
        // TODO add your handling code here:
        //---- PROPIETARIO
        Propietario pod = new Propietario();
        ConsultasPropietario podP = new ConsultasPropietario ();
        Vista.frmPropietario frmP = new Vista.frmPropietario();

        CtrPropietario ctrl = new CtrPropietario(pod,podP,frmP);
        ctrl.iniciar();
        this.setEnabled(false);
        //-----------------

        frmP.setVisible(true);
    }//GEN-LAST:event_jButtoNuevoMouseClicked

    private void jButtoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromMenu().setVisible(true);
                
            }
        });
        
        
     
    }
    
    public void enabledPanel (boolean flag){
         this.setVisible(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtoNuevo;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JPanel jPanelContrato;
    private javax.swing.JPanel jPanelInmueble;
    private javax.swing.JPanel jPanelInquilino;
    private javax.swing.JPanel jPanelPropietario;
    public javax.swing.JTabbedPane jTabbedPaneMenu;
    private Vista.Propietario.panelPropietarioList panelPropietarioList1;
    // End of variables declaration//GEN-END:variables
}
